services:
  frontend:
    build: ./frontend
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    # volumes:
    #   - ./frontend:/app/frontend
    develop:
      watch:
        - action: sync
          path: ./frontend/nice-cards
          target: /app/frontend/nice-cards
          ignore:
            - node_modules/
        - action: rebuild
          path: frontend/nice-cards/package.json
  backend:
    build: ./backend
    command: npm run dev
    ports:
      - "5200:5200"
    # volumes:
    #   - ./backend:/app/backend
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
          ignore:
            - node_modules/
        - action: rebuild
          path: backend/package.json
